blank_issues_enabled: false
contact_links:
  - name: 🌐 Site do Curso
    url: https://si-uninta.github.io
    about: Acesse o portal do curso para materiais e recursos
  - name: 🏫 UNINTA Tianguá
    url: https://uninta.edu.br
    about: Site oficial da instituição
